/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;

/**
 *
 * @author DAM-2
 */
public class VistaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelBotones = new javax.swing.JPanel();
        botonAlta = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonConsultar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 0));
        setLayout(new java.awt.BorderLayout());

        PanelBotones.setBackground(new java.awt.Color(229, 250, 255));
        PanelBotones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ITVSEGURO", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        PanelBotones.setPreferredSize(new java.awt.Dimension(520, 400));
        PanelBotones.setLayout(new java.awt.GridBagLayout());

        botonAlta.setText("ALTA");
        botonAlta.setToolTipText("Dar de alta nuevo coche");
        botonAlta.setPreferredSize(new java.awt.Dimension(200, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PanelBotones.add(botonAlta, gridBagConstraints);

        botonSalir.setText("SALIR");
        botonSalir.setPreferredSize(new java.awt.Dimension(100, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        PanelBotones.add(botonSalir, gridBagConstraints);

        botonConsultar.setText("CONSULTAR");
        botonConsultar.setToolTipText("Consultar coches ya introducidos");
        botonConsultar.setPreferredSize(new java.awt.Dimension(200, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PanelBotones.add(botonConsultar, gridBagConstraints);

        add(PanelBotones, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    public void addControlador(ActionListener al){
        botonAlta.addActionListener(al);
        botonConsultar.addActionListener(al);
        botonSalir.addActionListener(al);
        
        botonAlta.setActionCommand("Alta");
        botonConsultar.setActionCommand("Consultar");
        botonSalir.setActionCommand("Salir");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JButton botonAlta;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonSalir;
    // End of variables declaration//GEN-END:variables
}
