/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.GridLayout;

/**
 *
 * @author samuel
 */
public class VistaVerITV extends javax.swing.JPanel {

    public VistaConsultarTabla vistaTabla;
    /**
     * Creates new form VistaVerITV
     */
    public VistaVerITV() {
        initComponents();
        
        vistaTabla = new VistaConsultarTabla();
        add(vistaTabla, 0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonModificar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jButtonModificar.setText("MODIFICAR");
        jButtonModificar.setToolTipText("Modificar fecha ITV del coche");
        jButtonModificar.setAlignmentX(25.0F);
        jButtonModificar.setAlignmentY(30.0F);
        jButtonModificar.setMaximumSize(new java.awt.Dimension(150, 40));
        jPanel2.add(jButtonModificar);

        jButtonSalir.setText("SALIR");
        jButtonSalir.setToolTipText("Salir o volver atrás");
        jButtonSalir.setAlignmentX(20.0F);
        jButtonSalir.setAlignmentY(10.0F);
        jButtonSalir.setMaximumSize(new java.awt.Dimension(100, 40));
        jPanel2.add(jButtonSalir);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

   
}
