/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author samuel
 */
public class VistaVehiculos extends javax.swing.JPanel {

   public VistaConsultarTabla vistaTabla;
   
    public VistaVehiculos() {
        initComponents();
        
        vistaTabla = new VistaConsultarTabla();
        this.add(vistaTabla, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTablaVehiculos = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        panelTablaVehiculos.setBackground(new java.awt.Color(229, 250, 255));
        panelTablaVehiculos.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla datos del Vehiculo"));

        javax.swing.GroupLayout panelTablaVehiculosLayout = new javax.swing.GroupLayout(panelTablaVehiculos);
        panelTablaVehiculos.setLayout(panelTablaVehiculosLayout);
        panelTablaVehiculosLayout.setHorizontalGroup(
            panelTablaVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        panelTablaVehiculosLayout.setVerticalGroup(
            panelTablaVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        add(panelTablaVehiculos, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelTablaVehiculos;
    // End of variables declaration//GEN-END:variables


}
