/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author samuel
 */
public class VistaCocheAlta extends JPanel {
    
    public VistaCocheAlta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFormulario = new javax.swing.JPanel();
        etiquetaMarca = new javax.swing.JLabel();
        jTextFieldMarca = new javax.swing.JTextField();
        etiquetaModelo = new javax.swing.JLabel();
        jTextFieldModelo = new javax.swing.JTextField();
        etiquetaMatricula = new javax.swing.JLabel();
        jFormattedTextMatricula = new javax.swing.JFormattedTextField();
        etiquetaTipoRevision = new javax.swing.JLabel();
        listaTipoRevision = new javax.swing.JComboBox<>();
        etiquetaFechaRevision = new javax.swing.JLabel();
        jFormattedTextFechaRevision = new javax.swing.JFormattedTextField();
        etiquetaFechaSeguro = new javax.swing.JLabel();
        jFormattedTextFechaSeguro = new javax.swing.JFormattedTextField();
        etiquetaPrecioSeguro = new javax.swing.JLabel();
        jTextFieldPrecioSeguro = new javax.swing.JTextField();
        jPanelBotones = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanelFormulario.setBackground(new java.awt.Color(229, 250, 255));
        jPanelFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del vehiculo"));
        jPanelFormulario.setLayout(new java.awt.GridLayout(7, 2));

        etiquetaMarca.setText("Marca");
        jPanelFormulario.add(etiquetaMarca);
        jPanelFormulario.add(jTextFieldMarca);

        etiquetaModelo.setText("Modelo");
        jPanelFormulario.add(etiquetaModelo);
        jPanelFormulario.add(jTextFieldModelo);

        etiquetaMatricula.setText("Matricula");
        jPanelFormulario.add(etiquetaMatricula);

        try {
            jFormattedTextMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-UUU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelFormulario.add(jFormattedTextMatricula);

        etiquetaTipoRevision.setText("TipoRevision");
        jPanelFormulario.add(etiquetaTipoRevision);

        listaTipoRevision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6 meses", "1 año", "2 años", "4 años" }));
        jPanelFormulario.add(listaTipoRevision);

        etiquetaFechaRevision.setText("Fecha útima revisión");
        jPanelFormulario.add(etiquetaFechaRevision);

        try {
            jFormattedTextFechaRevision.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelFormulario.add(jFormattedTextFechaRevision);

        etiquetaFechaSeguro.setText("Última fecha seguro");
        jPanelFormulario.add(etiquetaFechaSeguro);

        try {
            jFormattedTextFechaSeguro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelFormulario.add(jFormattedTextFechaSeguro);

        etiquetaPrecioSeguro.setText("Precio seguro");
        jPanelFormulario.add(etiquetaPrecioSeguro);
        jPanelFormulario.add(jTextFieldPrecioSeguro);

        add(jPanelFormulario, java.awt.BorderLayout.CENTER);

        jPanelBotones.setBackground(new java.awt.Color(229, 250, 255));

        botonAceptar.setText("Aceptar");
        botonAceptar.setToolTipText("Aceptar alta de nuevo vehiculo");

        botonCancelar.setText("Canclear");
        botonCancelar.setToolTipText("Volver atrás");

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanelBotones, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel etiquetaFechaRevision;
    private javax.swing.JLabel etiquetaFechaSeguro;
    private javax.swing.JLabel etiquetaMarca;
    private javax.swing.JLabel etiquetaMatricula;
    private javax.swing.JLabel etiquetaModelo;
    private javax.swing.JLabel etiquetaPrecioSeguro;
    private javax.swing.JLabel etiquetaTipoRevision;
    private javax.swing.JFormattedTextField jFormattedTextFechaRevision;
    private javax.swing.JFormattedTextField jFormattedTextFechaSeguro;
    private javax.swing.JFormattedTextField jFormattedTextMatricula;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldPrecioSeguro;
    private javax.swing.JComboBox<String> listaTipoRevision;
    // End of variables declaration//GEN-END:variables
    
    public void addManejador(ActionListener e) {

        botonAceptar.addActionListener(e);
        botonCancelar.addActionListener(e);
       
        botonAceptar.setActionCommand("Aceptar");
        botonCancelar.setActionCommand("Cancelar");
    }
    public String getMarca() {
        return jTextFieldMarca.getText();
    }
    public String getModelo() {
        return jTextFieldModelo.getText();
    }
    
    public String getMatricula() {
        return jFormattedTextMatricula.getText();
    }
    public String getTipoRevision() {
        return etiquetaMatricula.getText();
    }
    
    public String getListaTipoRevision(){
        return listaTipoRevision.getSelectedItem().toString();
    }
    
    public String getFechaITV() {
        return jFormattedTextFechaRevision.getText();
    }
    public String getFechaSeguro() {
        return jFormattedTextFechaSeguro.getText();
    }
    
    public Double getPrecioSeguro() {
        
        double numeroPrecio = 0;
        String precio;
        
        precio = jTextFieldPrecioSeguro.getText();
        
        if(precio == null || precio.equals("")){
            System.out.println("Error de formato del precio");
        }
        
        numeroPrecio = Double.parseDouble(precio);
      
        return numeroPrecio;
    }
}
